---
abstract: 'Build docker image and upload to docker hub'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  perl: v5.20.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.20.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-DockerHub
provides:
  Dist::Zilla::Plugin::Docker:
    file: lib/Dist/Zilla/Plugin/Docker.pm
    version: '0.01'
  Dist::Zilla::Plugin::Docker::DockerClient:
    file: lib/Dist/Zilla/Plugin/Docker/DockerClient.pm
    version: '0.01'
requires:
  Archive::Tar: '0'
  DateTime: '0'
  Dist::Zilla::Path: '0'
  Dist::Zilla::Role::Releaser: '0'
  File::pushd: '0'
  Moose: '0'
  String::Formatter: '0'
  namespace::autoclean: '0'
  perl: v5.20.0
  strict: '0'
  warnings: '0'
resources: {}
version: '0.01'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
